name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      # Flatpak files
      - "**.yml"
      - "**.toml"
      - "scripts/**"
      - "shared-modules/**"

      # Workflows
      - ".github/workflows/build.yml"
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: Build (${{ matrix.arch }})

    permissions:
      contents: read

    strategy:
      fail-fast: false
      # WARN(@getchoo): DON'T REMOVE THIS!
      # We share and incrementally update a repository with each subsequent build
      # Having builds run in parallel would overwrite the repository with only one build
      # TODO: Figure out how to not limit this when we aren't worried about the repository (i.e., PRs)
      max-parallel: 1
      matrix:
        include:
          - os: ubuntu-24.04
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64

    runs-on: ${{ matrix.os }}

    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-6.10
      options: --privileged
      volumes:
        - /opt/hostedtoolcache:/hostedtoolcache

    steps:
      - name: Free up disk space
        shell: bash
        run: |
          rm -rf /hostedtoolcache/*

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Set short version
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          UPSTREAM_SHA="$(gh api /repos/PrismLauncher/PrismLauncher/branches/develop --jq '.commit.sha')"
          echo "VERSION=${UPSTREAM_SHA::7}" >> "$GITHUB_ENV"

      - name: Get Date
        if: ${{ github.event_name == 'workflow_call' }}
        id: get-date
        shell: bash
        run: |
          echo "date=$(/bin/date -u '+%Y%m%d')" >> "$GITHUB_OUTPUT"

      - name: Restore local repository
        if: ${{ github.event_name == 'workflow_call' }}
        id: restore-repository
        uses: actions/cache/restore@v5
        with:
          path: repo/
          key: repository-${{ steps.get-date.outputs.date }}

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: org.prismlauncher.PrismLauncher.yml
          arch: ${{ matrix.arch }}
          branch: nightly
          bundle: PrismLauncher-${{ env.VERSION }}-${{ matrix.arch }}.flatpak

      - name: Update and prune repository
        if: ${{ github.event_name == 'workflow_call' }}
        shell: bash
        run: |
          flatpak build-update-repo --generate-static-deltas --prune repo/

      - name: Cache local repository
        if: ${{ github.event_name == 'workflow_call' }}
        uses: actions/cache/save@v5
        with:
          path: repo/
          key: ${{ steps.restore-repository.outputs.cache-primary-key }}
